server:
  port: 8080

database:
  host: postgres-coordinator
  port: 5432
  user: task_user
  password: task_password
  name: task_db

redis:
  addr: redis:6379
  password: ""
  db: 0

kafka:
  broker: kafka:9092