server:
  port: 8080

database:
  host: localhost
  port: 5432
  user: your_db_user
  password: your_db_password
  name: your_db_name  package config
  
  import (
      "log"
      "os"
  
      "gopkg.in/yaml.v2"
  )
  
  type Config struct {
      Server   ServerConfig   `yaml:"server"`
      Database DatabaseConfig `yaml:"database"`
  }
  
  type ServerConfig struct {
      Port int `yaml:"port"`
  }
  
  type DatabaseConfig struct {
      Host     string `yaml:"host"`
      Port     int    `yaml:"port"`
      User     string `yaml:"user"`
      Password string `yaml:"password"`
      Name     string `yaml:"name"`
  }
  
  func LoadConfig() (*Config, error) {
      file, err := os.Open("config/config.yaml")
      if err != nil {
          return nil, err
      }
      defer