server:
  port: 8080
  page_size: 20
  page: 1

database:
  host: postgres-coordinator
  port: 5432
  user: task_user
  password: task_password
  name: task_db

redis:
  addr: redis:6379
  password: ""
  db: 0

kafka:
  broker: kafka:9092
  group_id: task_group
  topics: ['task_create', 'task_update', 'task_delete']